ROOTPATH = ../../..
MODULE = initservice

OBJS =  initservice.o            \
		initservicetaskentry.o   \
		initservicevfs1.o        \
		initservicevfs2.o

SUBDIRS = test.d

include ${ROOTPATH}/config.mk
