ROOTPATH = ../../..

EXTRAINCDIR += ${ROOTPATH}/src/include/usr/ecmddatabuffer
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/fapi
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/plat

MODULE = isteps

OBJS = istep1.o

# SUBDIRS = test

include ${ROOTPATH}/config.mk
