/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: src/import/hwpf/sbe_utils/gentool/attrtool/templates/ody_sbe_attribute_data_size.H.t $ */
/*                                                                        */
/* OpenPOWER HostBoot Project                                             */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2023                             */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */

/**************************************************************************
 *
 * The content of this file has been generated using the jinja2
 * template ody_sbe_attribute_data_size.H. For any changes required,
 * please modify the template.
 *
 **************************************************************************/
#ifndef _ODY_SBE_ATTRIBUTE_DATA_SIZE_
#define _ODY_SBE_ATTRIBUTE_DATA_SIZE_

{#
 # The inputs to this template are attributes and the target_types from
 # the attribute tank object. These inputs are passed to via the
 # environment globals. The attribute tool creates the environment, sets
 # the globals, loads the template, and render it. The rendered template
 # is returned as a string to the attribute tool. The attribute tool then
 # stores the string in a file. The suffix ".t" is used to differentiate
 # between the generated file name, and the template file name.
 #}

// Generated by attrtool
//   1. calculate the size required for generating attribute update file based on
//      the number of attributes need to be synced.
//   // TODO : Assume 75% compression ratio and store in the macro below.
#define ODY_GENERATE_ATTR_DATA_SIZE {{attr_data.attr_upd_blob_size}}u

// The buffer size required for storing the attribute list chip-op response.
// It is difficult to calculate the size of this buffer as the size will
// vary based on the SBE version.
// The atribute list response size is 21K. For a safer side, making it as
// 32K.
#define ODY_ATTR_LIST_CHIPOP_MAX_SIZE (32*1024)

#endif
