/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: src/import/chips/ocmb/odyssey/procedures/hwp/utils/ody_apply_sbe_attribute_data.C $ */
/*                                                                        */
/* OpenPOWER HostBoot Project                                             */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2023                             */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */
#include <ody_apply_sbe_attribute_data.H>

using namespace fapi2;
using namespace sbeutil;

///////////////////// MACROs used for continue on error /////////////////////////////////
#define VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE)                          \
    if (l_rc != FAPI2_RC_SUCCESS)                                           \
    {                                                                       \
        FAPI_ERR("convertToFapiTargetWrap failed for " #TARGET_TYPE);       \
        FAPI_TRY(l_targ_reader.addAttributesToError(                        \
                 SBE_ATTRIBUTE_RC_TGT_TYPE_NOT_FOUND, o_errors),         \
                 "addAttributesToError failed for an unknown target type"); \
        break;                                                              \
    }
///////////////////////////////////////////////////////////////////////////////////////

// forward declaration of functions which will apply the attributes
//    These functions for each target will be autogenerated below.
template<TargetType T>
ReturnCode ody_apply_sbe_attribute_row(
    Target<T>& i_targ, SbeAttrTargetSectionListRespParser& i_targ_parser, std::vector<AttrError_t>& o_errors);

// Generated code begins here
////////////////////////////////////////////////////////////////////////

#include <ody_apply_attribute_generated.C>

////////////////////////////////////////////////////////////////////////
// Generated code ends here


extern "C"
{

    ReturnCode ody_apply_sbe_attribute_data(
        const Target<TARGET_TYPE_OCMB_CHIP>& i_ocmb_targ,
        uint8_t* i_buf,
        uint16_t i_buf_size,
        std::vector<AttrError_t>& o_errors)
    {
        FAPI_DBG("ody_apply_sbe_attribute_data Entering");

        SbeAttributeListRespFileParser l_reader;
        ReturnCode l_rc = FAPI2_RC_SUCCESS;

        FAPI_TRY(l_reader.setChipTarget(i_ocmb_targ), "setChipTarget failed");
        FAPI_TRY(l_reader.parseFile(i_buf, i_buf_size), "parseFile failed");
        FAPI_DBG("----------------- PARSING DONE ------------");

        while(l_reader.getRemainingTargSectionCount())
        {
            FAPI_DBG("l_reader.getRemainingTargSectionCount() = %d", l_reader.getRemainingTargSectionCount());
            SbeTarget l_sbe_target;
            SbeAttrTargetSectionListRespParser& l_targ_reader = l_reader.getNextTargetSection(l_sbe_target);
            FAPI_DBG("l_sbe_target.iv_chip_type = %d", l_sbe_target.iv_chip_type);
            FAPI_DBG("l_sbe_target.iv_targ_type = %d", l_sbe_target.iv_targ_type);
            FAPI_DBG("l_sbe_target.iv_inst_num = %d", l_sbe_target.iv_inst_num);

            switch (l_sbe_target.iv_targ_type)
            {
                case LOG_TARGET_TYPE_SYSTEM:
                    {
                        Target<TARGET_TYPE_SYSTEM> l_targ;
                        l_rc = l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ);

                        VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE_SYSTEM);

                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader, o_errors),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_SYSTEM");
                        break;
                    }

                case LOG_TARGET_TYPE_OCMB_CHIP:
                    {
                        Target<TARGET_TYPE_OCMB_CHIP> l_targ;
                        l_rc = l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ);

                        VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE_OCMB_CHIP);

                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader, o_errors),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_OCMB_CHIP");
                        break;
                    }

                case LOG_TARGET_TYPE_PERV:
                    {
                        Target<TARGET_TYPE_PERV> l_targ;
                        l_rc = l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ);

                        VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE_PERV);

                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader, o_errors),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_PERV");
                        break;
                    }

                case LOG_TARGET_TYPE_MEM_PORT:
                    {
                        Target<TARGET_TYPE_MEM_PORT> l_targ;
                        l_rc = l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ);

                        VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE_MEM_PORT);

                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader, o_errors),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_MEM_PORT");
                        break;
                    }

                case LOG_TARGET_TYPE_DIMM:
                    {
                        Target<TARGET_TYPE_DIMM> l_targ;
                        l_rc = l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ);

                        VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE_DIMM);

                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader, o_errors),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_DIMM");
                        break;
                    }

                case LOG_TARGET_TYPE_TEMP_SENSOR:
                    {
                        Target<TARGET_TYPE_TEMP_SENSOR> l_targ;
                        l_rc = l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ);

                        VERIFY_SBE_FAPI_TGT_CREATE_RC(TARGET_TYPE_TEMP_SENSOR);

                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader, o_errors),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_TEMP_SENSOR");
                        break;
                    }

                default:
                    FAPI_ERR("Unknown LOG_TARGET_TYPE : %d. Instance num : %d",
                             l_sbe_target.iv_targ_type, l_sbe_target.iv_inst_num);

                    // Here, the assumption is that the data contains valid fapi2::LogTargetType
                    // and the procedure is not handling that target type.
                    FAPI_TRY(l_targ_reader.addAttributesToError(SBE_ATTRIBUTE_RC_TGT_TYPE_NOT_FOUND,
                             o_errors),
                             "addAttributesToError failed for an unknown target type");
                    break;
            }
        }

    fapi_try_exit:
        return current_err;
    }

} // extern C
