/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: src/import/chips/ocmb/odyssey/procedures/hwp/utils/ody_apply_sbe_attribute_data.C $ */
/*                                                                        */
/* OpenPOWER HostBoot Project                                             */
/*                                                                        */
/* Contributors Listed Below - COPYRIGHT 2023                             */
/* [+] International Business Machines Corp.                              */
/*                                                                        */
/*                                                                        */
/* Licensed under the Apache License, Version 2.0 (the "License");        */
/* you may not use this file except in compliance with the License.       */
/* You may obtain a copy of the License at                                */
/*                                                                        */
/*     http://www.apache.org/licenses/LICENSE-2.0                         */
/*                                                                        */
/* Unless required by applicable law or agreed to in writing, software    */
/* distributed under the License is distributed on an "AS IS" BASIS,      */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or        */
/* implied. See the License for the specific language governing           */
/* permissions and limitations under the License.                         */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */
#include "ody_apply_sbe_attribute_data.H"

using namespace fapi2;
using namespace sbeutil;

// formward declaration of functions which will apply the attributes
//    These functions for each target will be autogenerated below.
template<TargetType T>
ReturnCode ody_apply_sbe_attribute_row(
    Target<T>& i_targ, SbeAttrTargetSectionListRespParser& i_targ_parser);

///////////////// Auto Generated Code //////////////////////////////////////////
template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_DIMM>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_DIMM> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_BAD_DQ_BITMAP:
                ATTR_BAD_DQ_BITMAP_Type l_val;
                FAPI_TRY(l_attr.getAttrValue(&l_val, sizeof(ATTR_BAD_DQ_BITMAP_Type),
                                             sizeof(uint8_t)),
                         "getAttrValue failed for attribute ATTR_BAD_DQ_BITMAP");
                FAPI_TRY(FAPI_ATTR_SET(ATTR_BAD_DQ_BITMAP, i_targ, l_val),
                         "FAPI_ATTR_SET failed for attribute ATTR_BAD_DQ_BITMAP");
                break;

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_SYSTEM>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_SYSTEM> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_HOTPLUG:
                ATTR_HOTPLUG_Type l_hotPlugVal;
                FAPI_TRY(l_attr.getAttrValue(&l_hotPlugVal, sizeof(ATTR_HOTPLUG_Type),
                                             sizeof(uint8_t)),
                         "getAttrValue failed for attribute ATTR_HOTPLUG");
                FAPI_TRY(FAPI_ATTR_SET(ATTR_HOTPLUG, i_targ, l_hotPlugVal),
                         "FAPI_ATTR_SET failed for attribute ATTR_HOTPLUG");
                break;

            case ATTR_OCMB_BOOT_FLAGS:
                ATTR_OCMB_BOOT_FLAGS_Type l_bootFlagVal;
                FAPI_TRY(l_attr.getAttrValue(&l_bootFlagVal,
                                             sizeof(ATTR_OCMB_BOOT_FLAGS_Type), sizeof(uint32_t)),
                         "getAttrValue failed for attribute ATTR_OCMB_BOOT_FLAGS");
                FAPI_TRY(FAPI_ATTR_SET(ATTR_OCMB_BOOT_FLAGS, i_targ, l_bootFlagVal),
                         "FAPI_ATTR_SET failed for attribute ATTR_OCMB_BOOT_FLAGS");
                break;

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_OCMB_CHIP>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_OCMB_CHIP> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_OCMB_PLL_BUCKET:
                ATTR_OCMB_PLL_BUCKET_Type l_val;
                FAPI_TRY(l_attr.getAttrValue(&l_val, sizeof(ATTR_OCMB_PLL_BUCKET_Type),
                                             sizeof(uint8_t)),
                         "getAttrValue failed for attribute ATTR_OCMB_PLL_BUCKET");
                FAPI_TRY(FAPI_ATTR_SET(ATTR_OCMB_PLL_BUCKET, i_targ, l_val),
                         "FAPI_ATTR_SET failed for attribute ATTR_OCMB_PLL_BUCKET");
                break;

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_PERV>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_PERV> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_PG:
                ATTR_PG_Type l_val;
                FAPI_TRY(l_attr.getAttrValue(&l_val, sizeof(ATTR_PG_Type), sizeof(uint32_t)),
                         "getAttrValue failed for attribute ATTR_PG");
                FAPI_TRY(FAPI_ATTR_SET(ATTR_PG, i_targ, l_val),
                         "FAPI_ATTR_SET failed for attribute ATTR_PG");
                break;

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_MEM_PORT>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_MEM_PORT> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_DDR5_DRAM_DQS_RTT_PARK:
                {
                    ATTR_DDR5_DRAM_DQS_RTT_PARK_Type l_val;
                    FAPI_TRY(l_attr.getAttrValue(&l_val,
                                                 sizeof(ATTR_DDR5_DRAM_DQS_RTT_PARK_Type), sizeof(uint8_t)),
                             "getAttrValue failed for attribute ATTR_DDR5_DRAM_DQS_RTT_PARK");

                    for(int i = 0; i < 2; i++)
                    {
                        for(int j = 0; j < 4; j++)
                        {
                            for(int k = 0; k < 2; k++)
                            {
                                printf("l_val[%d][%d][%d] = 0x%02X\n", i, j, k, l_val[i][j][k]);
                            }
                        }
                    }

                    FAPI_TRY(FAPI_ATTR_SET(ATTR_DDR5_DRAM_DQS_RTT_PARK, i_targ, l_val),
                             "FAPI_ATTR_SET failed for attribute ATTR_DDR5_DRAM_DQS_RTT_PARK");
                    break;
                }

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_TEMP_SENSOR>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_TEMP_SENSOR> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_SPPE_TARGET_STATE: //attribute not writeable

                break;

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

template<>
ReturnCode ody_apply_sbe_attribute_row(
    Target<TARGET_TYPE_MC>& i_targ,
    SbeAttrTargetSectionListRespParser& i_targ_parser)
{
    FAPI_DBG("ody_apply_sbe_attribute_row<TARGET_TYPE_MC> entering");

    AttrEntry_t l_attrEntry;

    while (i_targ_parser.getRemainingRowCount())
    {
        FAPI_DBG("getRemainingRowCount() = %d", i_targ_parser.getRemainingRowCount());

        SbeAttrRowListResParser& l_attr = i_targ_parser.getNextRow();
        FAPI_TRY(l_attr.getAttrEntry(l_attrEntry), "getAttrEntry returned error");

        switch (l_attrEntry.iv_attrId)
        {
            case ATTR_FAPI_POS: //attribute not writeable

                break;

            /***********************************************************
             If an attribute is marked as DO_NOT_XMIT_TO_HOST, then
             it is a NO-OP.

             case ATTR_TEST:

                 FAPI_INFO("ATTR_TEST is marked as DO_NOT_XMIT_TO_HOST");
                 break;

             ***********************************************************/
            default:
                // If SBE returns an attribute that hwp is not aware,
                // then assert it.
                FAPI_ASSERT(false, INVALID_ATTR_FILE(),
                            "Unknown attribute 0x%08X", l_attrEntry.iv_attrId);
                break;
        }
    }

fapi_try_exit:
    return current_err;
}

// Generated code ends here
/////////////////////////////////////////////////////////////////////////////////

extern "C"
{

    ReturnCode ody_apply_sbe_attribute_data(
        const Target<TARGET_TYPE_OCMB_CHIP>& i_ocmb_targ,
        uint8_t* i_buf,
        uint16_t i_buf_size,
        std::vector<AttrError_t>& o_errors)
    {
        FAPI_DBG("ody_apply_sbe_attribute_data Entering");

        SbeAttributeListRespFileParser l_reader;
        FAPI_TRY(l_reader.setChipTarget(i_ocmb_targ), "setChipTarget failed");
        FAPI_TRY(l_reader.parseFile(i_buf, i_buf_size), "parseFile failed");
        FAPI_DBG("----------------- PARSING DONE ------------");

        // TODO: remove after complete implementation
        l_reader.printMe();

        while(l_reader.getRemainingTargSectionCount())
        {
            FAPI_DBG("l_reader.getRemainingTargSectionCount() = %d", l_reader.getRemainingTargSectionCount());
            SbeTarget l_sbe_target;
            SbeAttrTargetSectionListRespParser& l_targ_reader = l_reader.getNextTargetSection(l_sbe_target);
            FAPI_DBG("l_sbe_target.iv_chip_type = %d", l_sbe_target.iv_chip_type);
            FAPI_DBG("l_sbe_target.iv_targ_type = %d", l_sbe_target.iv_targ_type);
            FAPI_DBG("l_sbe_target.iv_inst_num = %d", l_sbe_target.iv_inst_num);

            switch (l_sbe_target.iv_targ_type)
            {
                case LOG_TARGET_TYPE_SYSTEM:
                    {
                        Target<TARGET_TYPE_SYSTEM> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_SYSTEM");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_SYSTEM");
                        break;
                    }

                case LOG_TARGET_TYPE_OCMB_CHIP:
                    {
                        Target<TARGET_TYPE_OCMB_CHIP> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_OCMB_CHIP");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_OCMB_CHIP");
                        break;
                    }

                case LOG_TARGET_TYPE_PERV:
                    {
                        Target<TARGET_TYPE_PERV> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_PERV");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_PERV");
                        break;
                    }

                case LOG_TARGET_TYPE_MEM_PORT:
                    {
                        Target<TARGET_TYPE_MEM_PORT> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_MEM_PORT");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_MEM_PORT");
                        break;
                    }

                case LOG_TARGET_TYPE_MC:
                    {
                        Target<TARGET_TYPE_MC> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_MC");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_MC");
                        break;
                    }

                case LOG_TARGET_TYPE_DIMM:
                    {
                        Target<TARGET_TYPE_DIMM> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_DIMM");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_DIMM");
                        break;
                    }

                case LOG_TARGET_TYPE_TEMP_SENSOR:
                    {
                        Target<TARGET_TYPE_TEMP_SENSOR> l_targ;
                        FAPI_TRY(l_sbe_target.convertToFapiTargetWrap(i_ocmb_targ, l_targ),
                                 "convertToFapiTargetWrap failed for TARGET_TYPE_TEMP_SENSOR");
                        FAPI_TRY(ody_apply_sbe_attribute_row(l_targ, l_targ_reader),
                                 "ody_apply_sbe_attribute_row failed for TARGET_TYPE_TEMP_SENSOR");
                        break;
                    }

                default:
                    FAPI_ERR("Unknown LOG_TARGET_TYPE : %d. Instance num : %d",
                             l_sbe_target.iv_targ_type, l_sbe_target.iv_inst_num);
                    return SBE_ATTRIBUTE_UPDATE_TGT_TYPE_NOT_FOUND;
            }
        }

    fapi_try_exit:
        return current_err;
    }

} // extern C
