ROOTPATH = ../../../..
MODULE = fapi

EXTRAINCDIR += ${ROOTPATH}/src/include/usr/ecmddatabuffer
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/fapi
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/plat

OBJS =  fapiAttributeService.o \
        fapiReturnCode.o \
        fapiReturnCodeDataRef.o \
        fapiTarget.o

include ${ROOTPATH}/config.mk
