ROOTPATH = ../../../..

EXTRAINCDIR += ${ROOTPATH}/src/include/usr/ecmddatabuffer
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/fapi
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/plat

MODULE = testhwpf
TESTS = *.H

include ${ROOTPATH}/config.mk

