#!/bin/sh

if [ -f /var/lib/pldm/PHYP-NVRAM-CKSUM ]; then
    mv /var/lib/pldm/PHYP-NVRAM-CKSUM /var/lib/phosphor-software-manager/hostfw/nvram/PHYP-NVRAM-CKSUM;
else
    truncate -s 16 /var/lib/phosphor-software-manager/hostfw/nvram/PHYP-NVRAM-CKSUM
fi
