//  IBM_PROLOG_BEGIN_TAG
//  This is an automatically generated prolog.
//
//  $Source: src/usr/errl/plugins/errlParse.C $
//
//  IBM CONFIDENTIAL
//
//  COPYRIGHT International Business Machines Corp. 2012
//
//  p1
//
//  Object Code Only (OCO) source materials
//  Licensed Internal Code Source Materials
//  IBM HostBoot Licensed Internal Code
//
//  The source code for this program is not published or other-
//  wise divested of its trade secrets, irrespective of what has
//  been deposited with the U.S. Copyright Office.
//
//  Origin: 30
//
//  IBM_PROLOG_END

/**
 *  @file initsvcParse.C
 *
 *  errl user detail data and src parser
 */

//------------------------------------------------------------------------------
// User detail data parser
//------------------------------------------------------------------------------
#include "symbols.H"
#include <errl/errludparser.H>
#include <errl/errludparserfactoryerrl.H>
ERRL_MAKE_UD_PARSER(ERRORLOG::ErrlUserDetailsParserFactoryErrl, HBERRL_COMP_ID)

//------------------------------------------------------------------------------
// Src parser (call code generated by scanforsrc.pl)
//------------------------------------------------------------------------------

// FSP include
#include <srcisrc.H>

// Hostboot include
#include <hostBootSrcParse.H>

static bool hbSrcParse( ErrlUsrParser & i_parser, const SrciSrc & i_src  )
{
  uint32_t src = 0;

  sscanf( i_src.getAsciiString(), "%X", &src );

  // Call this function in obj/genfiles/hostBootSrcParse.H (a script-generated
  // file) which serves for any Hostboot component.   This will cause
  // the FSP errl tool to add the tagged information to the primary SRC
  // section of the error log. For example, the developer description
  // (devdesc) tag and associated info as well as the other tags describing
  // the userdata1 and userdata2 words.
  printErrorTags( i_parser, (src & 0xFFFF), i_src.moduleId()  );

  return false;
}

// Create an instance of SrcPlugin by type (instead of the usual component).
static errl::SrcPlugin  g_SrcPlugin( errl::Plugin::HOSTBOOT_SRCPARSE, hbSrcParse );

