/* IBM_PROLOG_BEGIN_TAG                                                   */
/* This is an automatically generated prolog.                             */
/*                                                                        */
/* $Source: src/usr/runtime/common/hsvc_procdata.C $                      */
/*                                                                        */
/* IBM CONFIDENTIAL                                                       */
/*                                                                        */
/* COPYRIGHT International Business Machines Corp. 2012                   */
/*                                                                        */
/* p1                                                                     */
/*                                                                        */
/* Object Code Only (OCO) source materials                                */
/* Licensed Internal Code Source Materials                                */
/* IBM HostBoot Licensed Internal Code                                    */
/*                                                                        */
/* The source code for this program is not published or otherwise         */
/* divested of its trade secrets, irrespective of what has been           */
/* deposited with the U.S. Copyright Office.                              */
/*                                                                        */
/* Origin: 30                                                             */
/*                                                                        */
/* IBM_PROLOG_END_TAG                                                     */
// Generated on Wed Oct 17 08:41:32 CDT 2012 by dcrowell from 
// -- Input: src/usr/runtime/common/extra_runtime_attributes.xml --
HSVC_LOAD_ATTR( ATTR_CHIP_ID );
HSVC_LOAD_ATTR( ATTR_FUNCTIONAL );
// -- Input: src/usr/hwpf/hwp/runtime_attributes/pm_attributes_all_plat.xml --
HSVC_LOAD_ATTR( ATTR_PROC_DCM_INSTALLED );
HSVC_LOAD_ATTR( ATTR_PM_EXTERNAL_VRM_STEPSIZE );
HSVC_LOAD_ATTR( ATTR_PM_EXTERNAL_VRM_STEPDELAY );
HSVC_LOAD_ATTR( ATTR_PM_SAFE_VOLTAGE );
HSVC_LOAD_ATTR( ATTR_PM_PSTATE_UNDERVOLTING_MINIMUM );
HSVC_LOAD_ATTR( ATTR_PM_PSTATE_UNDERVOLTING_MAXIMUM );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_PORT_ENABLE );
HSVC_LOAD_ATTR( ATTR_PM_SLEEP_ENTRY );
HSVC_LOAD_ATTR( ATTR_PM_SLEEP_EXIT );
HSVC_LOAD_ATTR( ATTR_PM_SLEEP_TYPE );
HSVC_LOAD_ATTR( ATTR_PM_WINKLE_ENTRY );
HSVC_LOAD_ATTR( ATTR_PM_WINKLE_EXIT );
HSVC_LOAD_ATTR( ATTR_PM_WINKLE_TYPE );
HSVC_LOAD_ATTR( ATTR_PM_SAFE_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_FULL_CLOCK_SECTOR_BUFFER_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_LOW_BAND_LOWER_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_LOW_BAND_UPPER_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_HIGH_BAND_LOWER_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_HIGH_BAND_UPPER_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_APSS_CHIP_SELECT );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_NODEID );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_CHIPID );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_BRDCST_ID_VECTOR );
// -- Input: src/usr/hwpf/hwp/runtime_attributes/pm_attributes_all_hwp.xml --
HSVC_LOAD_ATTR( ATTR_PM_POWER_PROXY_TRACE_TIMER );
HSVC_LOAD_ATTR( ATTR_PM_PPT_TIMER_MATCH_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PPT_TIMER_TICK );
HSVC_LOAD_ATTR( ATTR_PM_AISS_TIMEOUT );
HSVC_LOAD_ATTR( ATTR_PM_PSTATE_STEPSIZE );
HSVC_LOAD_ATTR( ATTR_PM_EXTERNAL_VRM_STEPDELAY_RANGE );
HSVC_LOAD_ATTR( ATTR_PM_EXTERNAL_VRM_STEPDELAY_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PMC_HANGPULSE_DIVIDER );
HSVC_LOAD_ATTR( ATTR_PM_PVSAFE_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_FRAME_SIZE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_IN_DELAY_FRAME1 );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_IN_DELAY_FRAME2 );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_CLOCK_POLARITY );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_CLOCK_PHASE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_CLOCK_DIVIDER );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_INTERFRAME_DELAY_WRITE_STATUS_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_INTER_RETRY_DELAY_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_INTER_RETRY_DELAY );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_CRC_GEN_ENABLE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_CRC_CHECK_ENABLE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_MAJORITY_VOTE_ENABLE );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_MAX_RETRIES );
HSVC_LOAD_ATTR( ATTR_PM_SPIVID_CRC_POLYNOMIAL_ENABLES );
HSVC_LOAD_ATTR( ATTR_PM_OCC_HEARTBEAT_TIME );
HSVC_LOAD_ATTR( ATTR_PM_SLEEP_WINKLE_REQUEST_TIMEOUT );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_CORE_DELAY0 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_CORE_DELAY1 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_CORE_DELAY0_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_CORE_DELAY1_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_CORE_SEQUENCE_DELAY_SELECT );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_CORE_DELAY0 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_CORE_DELAY1 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_CORE_DELAY0_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_CORE_DELAY1_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_CORE_SEQUENCE_DELAY_SELECT );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_ECO_DELAY0 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_ECO_DELAY1 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_ECO_DELAY0_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_ECO_DELAY1_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERUP_ECO_SEQUENCE_DELAY_SELECT );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_ECO_DELAY0 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_ECO_DELAY1 );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_ECO_DELAY0_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_ECO_DELAY1_VALUE );
HSVC_LOAD_ATTR( ATTR_PM_PFET_POWERDOWN_ECO_SEQUENCE_DELAY_SELECT );
HSVC_LOAD_ATTR( ATTR_PM_PSTATE0_FREQUENCY );
HSVC_LOAD_ATTR( ATTR_PM_IVRMS_ENABLED );
HSVC_LOAD_ATTR( ATTR_PM_SAFE_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_ENABLE );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_FULL_CSB_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_LFRLOW_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_LFRUPPER_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_HFRLOW_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_RESONANT_CLOCK_HFRHIGH_PSTATE );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_FRAME_SIZE );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_OUT_COUNT );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_IN_DELAY );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_IN_COUNT );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_CLOCK_POLARITY );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_CLOCK_PHASE );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_CLOCK_DIVIDER );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_INTER_FRAME_DELAY_SETTING );
HSVC_LOAD_ATTR( ATTR_PM_SPIPSS_INTER_FRAME_DELAY );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_RCV_RESERV_TIMEOUT );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_SND_RETRY_COUNT_OVERCOMMIT_ENABLE );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_SND_RETRY_THRESHOLD );
HSVC_LOAD_ATTR( ATTR_PM_PBAX_SND_RESERV_TIMEOUT );
