ROOTPATH = ../../../..
MODULE = plat

EXTRAINCDIR += ${ROOTPATH}/src/include/usr/ecmddatabuffer
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/plat
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/fapi
EXTRAINCDIR += ${ROOTPATH}/src/include/usr/hwpf/hwp

OBJS = fapiPlatHwAccess.o \
       fapiPlatHwpInvoker.o \
       fapiPlatReturnCodeDataRef.o \
       fapiPlatSystemConfig.o \
       fapiPlatTarget.o \
       fapiPlatUtil.o

include ${ROOTPATH}/config.mk
