//  IBM_PROLOG_BEGIN_TAG
//  This is an automatically generated prolog.
//
//  $Source: src/usr/hwpf/hwp/mc_init/mss_eff_config/mss_eff_config_sim.C $
//
//  IBM CONFIDENTIAL
//
//  COPYRIGHT International Business Machines Corp. 2012
//
//  p1
//
//  Object Code Only (OCO) source materials
//  Licensed Internal Code Source Materials
//  IBM HostBoot Licensed Internal Code
//
//  The source code for this program is not published or other-
//  wise divested of its trade secrets, irrespective of what has
//  been deposited with the U.S. Copyright Office.
//
//  Origin: 30
//
//  IBM_PROLOG_END
//------------------------------------------------------------------------------
// *! (C) Copyright International Business Machines Corp. 2011
// *! All Rights Reserved -- Property of IBM
// *! *** IBM Confidential ***
//------------------------------------------------------------------------------
// *! TITLE       : mss_eff_config_sim.C
// *! DESCRIPTION : This code was auto generated by mss_eff_config_sim_gen.pl
// *! OWNER NAME  : asaetow
// *! ADDITIONAL COMMENTS :
//
//    FOR SIM ONLY!
//
//------------------------------------------------------------------------------
// CHANGE HISTORY:
//------------------------------------------------------------------------------
// Version:|           Author:         |   Date:   | Comment:
//---------|---------------------------|-----------|----------------------------
//   X.X   | mss_eff_config_sim_gen.pl |29-Feb-2012| Machine generated code.


//----------------------------------------------------------------------
//  My Includes
//----------------------------------------------------------------------
#include <mss_eff_config_sim.H>


//----------------------------------------------------------------------
//  Includes
//----------------------------------------------------------------------
#include <fapi.H>


extern "C" {

//******************************************************************************
//* name=mss_eff_config_sim, param=i_target_mba, return=ReturnCode
//******************************************************************************
fapi::ReturnCode mss_eff_config_sim(const fapi::Target i_target_mba) {
   fapi::ReturnCode rc = fapi::FAPI_RC_SUCCESS;
   const char * const PROCEDURE_NAME = "mss_eff_config_sim";
   FAPI_INF("*** Running %s ... ***", PROCEDURE_NAME);
      uint8_t my_attr_eff_cen_drv_imp_cmd = 15;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_DRV_IMP_CMD, &i_target_mba, my_attr_eff_cen_drv_imp_cmd); if(rc) return rc;
      uint8_t my_attr_eff_cen_drv_imp_cntl = 15;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_DRV_IMP_CNTL, &i_target_mba, my_attr_eff_cen_drv_imp_cntl); if(rc) return rc;
      uint8_t my_attr_eff_cen_drv_imp_dq_dqs = 24;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_DRV_IMP_DQ_DQS, &i_target_mba, my_attr_eff_cen_drv_imp_dq_dqs); if(rc) return rc;
      uint8_t my_attr_eff_cen_rcv_imp_dq_dqs = 15;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_RCV_IMP_DQ_DQS, &i_target_mba, my_attr_eff_cen_rcv_imp_dq_dqs); if(rc) return rc;
      uint32_t my_attr_eff_cen_rd_vref = 50000;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_RD_VREF, &i_target_mba, my_attr_eff_cen_rd_vref); if(rc) return rc;
      uint8_t my_attr_eff_cen_slew_rate_cmd = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_SLEW_RATE_CMD, &i_target_mba, my_attr_eff_cen_slew_rate_cmd); if(rc) return rc;
      uint8_t my_attr_eff_cen_slew_rate_cntl = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_SLEW_RATE_CNTL, &i_target_mba, my_attr_eff_cen_slew_rate_cntl); if(rc) return rc;
      uint8_t my_attr_eff_cen_slew_rate_dq_dqs = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_CEN_SLEW_RATE_DQ_DQS, &i_target_mba, my_attr_eff_cen_slew_rate_dq_dqs); if(rc) return rc;
      uint8_t my_attr_eff_dimm_ranks_configed[2][2];
      my_attr_eff_dimm_ranks_configed[0][0] = 0x80;
      my_attr_eff_dimm_ranks_configed[0][1] = 0x0;
      my_attr_eff_dimm_ranks_configed[1][0] = 0x80;
      my_attr_eff_dimm_ranks_configed[1][1] = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DIMM_RANKS_CONFIGED, &i_target_mba, my_attr_eff_dimm_ranks_configed); if(rc) return rc;
      uint64_t my_attr_eff_dimm_rcd_cntl_word_0_15[2][2];
      my_attr_eff_dimm_rcd_cntl_word_0_15[0][0] = 0x0000000000000000;
      my_attr_eff_dimm_rcd_cntl_word_0_15[0][1] = 0x0000000000000000;
      my_attr_eff_dimm_rcd_cntl_word_0_15[1][0] = 0x0000000000000000;
      my_attr_eff_dimm_rcd_cntl_word_0_15[1][1] = 0x0000000000000000;
      rc = FAPI_ATTR_SET(ATTR_EFF_DIMM_RCD_CNTL_WORD_0_15, &i_target_mba, my_attr_eff_dimm_rcd_cntl_word_0_15); if(rc) return rc;
      uint8_t my_attr_eff_dimm_size[2][2];
      my_attr_eff_dimm_size[0][0] = 0x4;
      my_attr_eff_dimm_size[0][1] = 0x0;
      my_attr_eff_dimm_size[1][0] = 0x4;
      my_attr_eff_dimm_size[1][1] = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DIMM_SIZE, &i_target_mba, my_attr_eff_dimm_size); if(rc) return rc;
      uint8_t my_attr_eff_dimm_type = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DIMM_TYPE, &i_target_mba, my_attr_eff_dimm_type); if(rc) return rc;
      uint8_t my_attr_eff_dram_al = 1;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_AL, &i_target_mba, my_attr_eff_dram_al); if(rc) return rc;
      uint8_t my_attr_eff_dram_asr = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_ASR, &i_target_mba, my_attr_eff_dram_asr); if(rc) return rc;
      uint8_t my_attr_eff_dram_bl = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_BL, &i_target_mba, my_attr_eff_dram_bl); if(rc) return rc;
      uint8_t my_attr_eff_dram_cl = 0xB;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_CL, &i_target_mba, my_attr_eff_dram_cl); if(rc) return rc;
      uint8_t my_attr_eff_dram_cwl = 0x8;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_CWL, &i_target_mba, my_attr_eff_dram_cwl); if(rc) return rc;
      uint8_t my_attr_eff_dram_density = 0x4;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_DENSITY, &i_target_mba, my_attr_eff_dram_density); if(rc) return rc;
      uint8_t my_attr_eff_dram_dll_enable = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_DLL_ENABLE, &i_target_mba, my_attr_eff_dram_dll_enable); if(rc) return rc;
      uint8_t my_attr_eff_dram_dll_ppd = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_DLL_PPD, &i_target_mba, my_attr_eff_dram_dll_ppd); if(rc) return rc;
      uint8_t my_attr_eff_dram_dll_reset = 1;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_DLL_RESET, &i_target_mba, my_attr_eff_dram_dll_reset); if(rc) return rc;
      uint8_t my_attr_eff_dram_gen = 1;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_GEN, &i_target_mba, my_attr_eff_dram_gen); if(rc) return rc;
      uint8_t my_attr_eff_dram_output_buffer = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_OUTPUT_BUFFER, &i_target_mba, my_attr_eff_dram_output_buffer); if(rc) return rc;
      uint8_t my_attr_eff_dram_pasr = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_PASR, &i_target_mba, my_attr_eff_dram_pasr); if(rc) return rc;
      uint8_t my_attr_eff_dram_rbt = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_RBT, &i_target_mba, my_attr_eff_dram_rbt); if(rc) return rc;
      uint8_t my_attr_eff_dram_ron[2][2];
      my_attr_eff_dram_ron[0][0] = 34;
      my_attr_eff_dram_ron[0][1] = 40;
      my_attr_eff_dram_ron[1][0] = 34;
      my_attr_eff_dram_ron[1][1] = 40;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_RON, &i_target_mba, my_attr_eff_dram_ron); if(rc) return rc;
      uint8_t my_attr_eff_dram_rtt_nom[2][2][4];
      my_attr_eff_dram_rtt_nom[0][0][0] = 0;
      my_attr_eff_dram_rtt_nom[0][0][1] = 0;
      my_attr_eff_dram_rtt_nom[0][0][2] = 0;
      my_attr_eff_dram_rtt_nom[0][0][3] = 0;
      my_attr_eff_dram_rtt_nom[0][1][0] = 0;
      my_attr_eff_dram_rtt_nom[0][1][1] = 0;
      my_attr_eff_dram_rtt_nom[0][1][2] = 0;
      my_attr_eff_dram_rtt_nom[0][1][3] = 0;
      my_attr_eff_dram_rtt_nom[1][0][0] = 0;
      my_attr_eff_dram_rtt_nom[1][0][1] = 0;
      my_attr_eff_dram_rtt_nom[1][0][2] = 0;
      my_attr_eff_dram_rtt_nom[1][0][3] = 0;
      my_attr_eff_dram_rtt_nom[1][1][0] = 0;
      my_attr_eff_dram_rtt_nom[1][1][1] = 0;
      my_attr_eff_dram_rtt_nom[1][1][2] = 0;
      my_attr_eff_dram_rtt_nom[1][1][3] = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_RTT_NOM, &i_target_mba, my_attr_eff_dram_rtt_nom); if(rc) return rc;
      uint8_t my_attr_eff_dram_rtt_wr[2][2][4];
      my_attr_eff_dram_rtt_wr[0][0][0] = 60;
      my_attr_eff_dram_rtt_wr[0][0][1] = 0;
      my_attr_eff_dram_rtt_wr[0][0][2] = 0;
      my_attr_eff_dram_rtt_wr[0][0][3] = 0;
      my_attr_eff_dram_rtt_wr[0][1][0] = 0;
      my_attr_eff_dram_rtt_wr[0][1][1] = 0;
      my_attr_eff_dram_rtt_wr[0][1][2] = 0;
      my_attr_eff_dram_rtt_wr[0][1][3] = 0;
      my_attr_eff_dram_rtt_wr[1][0][0] = 60;
      my_attr_eff_dram_rtt_wr[1][0][1] = 0;
      my_attr_eff_dram_rtt_wr[1][0][2] = 0;
      my_attr_eff_dram_rtt_wr[1][0][3] = 0;
      my_attr_eff_dram_rtt_wr[1][1][0] = 0;
      my_attr_eff_dram_rtt_wr[1][1][1] = 0;
      my_attr_eff_dram_rtt_wr[1][1][2] = 0;
      my_attr_eff_dram_rtt_wr[1][1][3] = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_RTT_WR, &i_target_mba, my_attr_eff_dram_rtt_wr); if(rc) return rc;
      uint8_t my_attr_eff_dram_srt = 1;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_SRT, &i_target_mba, my_attr_eff_dram_srt); if(rc) return rc;
      uint8_t my_attr_eff_dram_tdqs = 1;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TDQS, &i_target_mba, my_attr_eff_dram_tdqs); if(rc) return rc;
      uint8_t my_attr_eff_dram_tfaw = 0x18;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TFAW, &i_target_mba, my_attr_eff_dram_tfaw); if(rc) return rc;
      uint8_t my_attr_eff_dram_tm = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TM, &i_target_mba, my_attr_eff_dram_tm); if(rc) return rc;
      uint8_t my_attr_eff_dram_tras = 0x1C;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRAS, &i_target_mba, my_attr_eff_dram_tras); if(rc) return rc;
      uint8_t my_attr_eff_dram_trc = 0x27;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRC, &i_target_mba, my_attr_eff_dram_trc); if(rc) return rc;
      uint8_t my_attr_eff_dram_trcd = 0xB;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRCD, &i_target_mba, my_attr_eff_dram_trcd); if(rc) return rc;
      uint8_t my_attr_eff_dram_trfc = 0x80;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRFC, &i_target_mba, my_attr_eff_dram_trfc); if(rc) return rc;
      uint32_t my_attr_eff_dram_trfi = 0x00000C30;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRFI, &i_target_mba, my_attr_eff_dram_trfi); if(rc) return rc;
      uint8_t my_attr_eff_dram_trp = 0xB;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRP, &i_target_mba, my_attr_eff_dram_trp); if(rc) return rc;
      uint8_t my_attr_eff_dram_trrd = 0x5;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRRD, &i_target_mba, my_attr_eff_dram_trrd); if(rc) return rc;
      uint8_t my_attr_eff_dram_trtp = 0x6;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TRTP, &i_target_mba, my_attr_eff_dram_trtp); if(rc) return rc;
      uint8_t my_attr_eff_dram_twtr = 0x6;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_TWTR, &i_target_mba, my_attr_eff_dram_twtr); if(rc) return rc;
      uint8_t my_attr_eff_dram_width = 1;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_WIDTH, &i_target_mba, my_attr_eff_dram_width); if(rc) return rc;
      uint8_t my_attr_eff_dram_wr = 0xC;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_WR, &i_target_mba, my_attr_eff_dram_wr); if(rc) return rc;
      uint8_t my_attr_eff_dram_wr_lvl_enable = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_WR_LVL_ENABLE, &i_target_mba, my_attr_eff_dram_wr_lvl_enable); if(rc) return rc;
      uint32_t my_attr_eff_dram_wr_vref = 500;
      rc = FAPI_ATTR_SET(ATTR_EFF_DRAM_WR_VREF, &i_target_mba, my_attr_eff_dram_wr_vref); if(rc) return rc;
      uint32_t my_attr_eff_memcal_interval = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_MEMCAL_INTERVAL, &i_target_mba, my_attr_eff_memcal_interval); if(rc) return rc;
      uint8_t my_attr_eff_mpr_loc = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_MPR_LOC, &i_target_mba, my_attr_eff_mpr_loc); if(rc) return rc;
      uint8_t my_attr_eff_mpr_mode = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_MPR_MODE, &i_target_mba, my_attr_eff_mpr_mode); if(rc) return rc;
      uint8_t my_attr_eff_num_ranks_per_dimm[2][2];
      my_attr_eff_num_ranks_per_dimm[0][0] = 0x1;
      my_attr_eff_num_ranks_per_dimm[0][1] = 0x0;
      my_attr_eff_num_ranks_per_dimm[1][0] = 0x1;
      my_attr_eff_num_ranks_per_dimm[1][1] = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_NUM_RANKS_PER_DIMM, &i_target_mba, my_attr_eff_num_ranks_per_dimm); if(rc) return rc;
      uint8_t my_attr_eff_odt_rd[2][2][4];
      my_attr_eff_odt_rd[0][0][0] = 0x0;
      my_attr_eff_odt_rd[0][0][1] = 0x0;
      my_attr_eff_odt_rd[0][0][2] = 0x0;
      my_attr_eff_odt_rd[0][0][3] = 0x0;
      my_attr_eff_odt_rd[0][1][0] = 0x0;
      my_attr_eff_odt_rd[0][1][1] = 0x0;
      my_attr_eff_odt_rd[0][1][2] = 0x0;
      my_attr_eff_odt_rd[0][1][3] = 0x0;
      my_attr_eff_odt_rd[1][0][0] = 0x0;
      my_attr_eff_odt_rd[1][0][1] = 0x0;
      my_attr_eff_odt_rd[1][0][2] = 0x0;
      my_attr_eff_odt_rd[1][0][3] = 0x0;
      my_attr_eff_odt_rd[1][1][0] = 0x0;
      my_attr_eff_odt_rd[1][1][1] = 0x0;
      my_attr_eff_odt_rd[1][1][2] = 0x0;
      my_attr_eff_odt_rd[1][1][3] = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_ODT_RD, &i_target_mba, my_attr_eff_odt_rd); if(rc) return rc;
      uint8_t my_attr_eff_odt_wr[2][2][4];
      my_attr_eff_odt_wr[0][0][0] = 0x0;
      my_attr_eff_odt_wr[0][0][1] = 0x0;
      my_attr_eff_odt_wr[0][0][2] = 0x0;
      my_attr_eff_odt_wr[0][0][3] = 0x0;
      my_attr_eff_odt_wr[0][1][0] = 0x0;
      my_attr_eff_odt_wr[0][1][1] = 0x0;
      my_attr_eff_odt_wr[0][1][2] = 0x0;
      my_attr_eff_odt_wr[0][1][3] = 0x0;
      my_attr_eff_odt_wr[1][0][0] = 0x0;
      my_attr_eff_odt_wr[1][0][1] = 0x0;
      my_attr_eff_odt_wr[1][0][2] = 0x0;
      my_attr_eff_odt_wr[1][0][3] = 0x0;
      my_attr_eff_odt_wr[1][1][0] = 0x0;
      my_attr_eff_odt_wr[1][1][1] = 0x0;
      my_attr_eff_odt_wr[1][1][2] = 0x0;
      my_attr_eff_odt_wr[1][1][3] = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_ODT_WR, &i_target_mba, my_attr_eff_odt_wr); if(rc) return rc;
      uint8_t my_attr_eff_primary_rank_group0[2];
      my_attr_eff_primary_rank_group0[0] = 0x0;
      my_attr_eff_primary_rank_group0[1] = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_PRIMARY_RANK_GROUP0, &i_target_mba, my_attr_eff_primary_rank_group0); if(rc) return rc;
      uint8_t my_attr_eff_primary_rank_group1[2];
      my_attr_eff_primary_rank_group1[0] = 255;
      my_attr_eff_primary_rank_group1[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_PRIMARY_RANK_GROUP1, &i_target_mba, my_attr_eff_primary_rank_group1); if(rc) return rc;
      uint8_t my_attr_eff_primary_rank_group2[2];
      my_attr_eff_primary_rank_group2[0] = 255;
      my_attr_eff_primary_rank_group2[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_PRIMARY_RANK_GROUP2, &i_target_mba, my_attr_eff_primary_rank_group2); if(rc) return rc;
      uint8_t my_attr_eff_primary_rank_group3[2];
      my_attr_eff_primary_rank_group3[0] = 255;
      my_attr_eff_primary_rank_group3[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_PRIMARY_RANK_GROUP3, &i_target_mba, my_attr_eff_primary_rank_group3); if(rc) return rc;
      uint8_t my_attr_eff_quaternary_rank_group0[2];
      my_attr_eff_quaternary_rank_group0[0] = 255;
      my_attr_eff_quaternary_rank_group0[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_QUATERNARY_RANK_GROUP0, &i_target_mba, my_attr_eff_quaternary_rank_group0); if(rc) return rc;
      uint8_t my_attr_eff_quaternary_rank_group1[2];
      my_attr_eff_quaternary_rank_group1[0] = 255;
      my_attr_eff_quaternary_rank_group1[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_QUATERNARY_RANK_GROUP1, &i_target_mba, my_attr_eff_quaternary_rank_group1); if(rc) return rc;
      uint8_t my_attr_eff_quaternary_rank_group2[2];
      my_attr_eff_quaternary_rank_group2[0] = 255;
      my_attr_eff_quaternary_rank_group2[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_QUATERNARY_RANK_GROUP2, &i_target_mba, my_attr_eff_quaternary_rank_group2); if(rc) return rc;
      uint8_t my_attr_eff_quaternary_rank_group3[2];
      my_attr_eff_quaternary_rank_group3[0] = 255;
      my_attr_eff_quaternary_rank_group3[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_QUATERNARY_RANK_GROUP3, &i_target_mba, my_attr_eff_quaternary_rank_group3); if(rc) return rc;
      uint8_t my_attr_eff_schmoo_mode = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_SCHMOO_MODE, &i_target_mba, my_attr_eff_schmoo_mode); if(rc) return rc;
      uint8_t my_attr_eff_schmoo_param_valid = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_SCHMOO_PARAM_VALID, &i_target_mba, my_attr_eff_schmoo_param_valid); if(rc) return rc;
      uint8_t my_attr_eff_schmoo_test_valid = 0x0;
      rc = FAPI_ATTR_SET(ATTR_EFF_SCHMOO_TEST_VALID, &i_target_mba, my_attr_eff_schmoo_test_valid); if(rc) return rc;
      uint8_t my_attr_eff_secondary_rank_group0[2];
      my_attr_eff_secondary_rank_group0[0] = 255;
      my_attr_eff_secondary_rank_group0[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_SECONDARY_RANK_GROUP0, &i_target_mba, my_attr_eff_secondary_rank_group0); if(rc) return rc;
      uint8_t my_attr_eff_secondary_rank_group1[2];
      my_attr_eff_secondary_rank_group1[0] = 255;
      my_attr_eff_secondary_rank_group1[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_SECONDARY_RANK_GROUP1, &i_target_mba, my_attr_eff_secondary_rank_group1); if(rc) return rc;
      uint8_t my_attr_eff_secondary_rank_group2[2];
      my_attr_eff_secondary_rank_group2[0] = 255;
      my_attr_eff_secondary_rank_group2[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_SECONDARY_RANK_GROUP2, &i_target_mba, my_attr_eff_secondary_rank_group2); if(rc) return rc;
      uint8_t my_attr_eff_secondary_rank_group3[2];
      my_attr_eff_secondary_rank_group3[0] = 255;
      my_attr_eff_secondary_rank_group3[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_SECONDARY_RANK_GROUP3, &i_target_mba, my_attr_eff_secondary_rank_group3); if(rc) return rc;
      uint8_t my_attr_eff_tertiary_rank_group0[2];
      my_attr_eff_tertiary_rank_group0[0] = 255;
      my_attr_eff_tertiary_rank_group0[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_TERTIARY_RANK_GROUP0, &i_target_mba, my_attr_eff_tertiary_rank_group0); if(rc) return rc;
      uint8_t my_attr_eff_tertiary_rank_group1[2];
      my_attr_eff_tertiary_rank_group1[0] = 255;
      my_attr_eff_tertiary_rank_group1[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_TERTIARY_RANK_GROUP1, &i_target_mba, my_attr_eff_tertiary_rank_group1); if(rc) return rc;
      uint8_t my_attr_eff_tertiary_rank_group2[2];
      my_attr_eff_tertiary_rank_group2[0] = 255;
      my_attr_eff_tertiary_rank_group2[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_TERTIARY_RANK_GROUP2, &i_target_mba, my_attr_eff_tertiary_rank_group2); if(rc) return rc;
      uint8_t my_attr_eff_tertiary_rank_group3[2];
      my_attr_eff_tertiary_rank_group3[0] = 255;
      my_attr_eff_tertiary_rank_group3[1] = 255;
      rc = FAPI_ATTR_SET(ATTR_EFF_TERTIARY_RANK_GROUP3, &i_target_mba, my_attr_eff_tertiary_rank_group3); if(rc) return rc;
      uint32_t my_attr_eff_zqcal_interval = 0;
      rc = FAPI_ATTR_SET(ATTR_EFF_ZQCAL_INTERVAL, &i_target_mba, my_attr_eff_zqcal_interval); if(rc) return rc;
   FAPI_INF("%s COMPLETE", PROCEDURE_NAME);
   return rc;
}

} // extern "C"
